language: node_js
node_js:
  - "0.10"
  - "0.11"
matrix:
  exclude:
    - node_js: "0.10"
      env: TEST_ENV=browser
  allow_failures:
    - node_js: "0.11"
      env: TEST_ENV=browser
  fast_finish: true
env:
  matrix:
    - TEST_ENV=server
    - TEST_ENV=browser
  global:
    - secure: ieYcAISx7TgwPUpeZXn1JeAFICQB2sOo9xDrEITPUAIqZUKhNvXRGnpLFQFIhi2ov5N2+WLNK5TFLlahxm1U6DYSg6L+WJYLYMEyE5oriMDElOiE+jJhl/L8up4zH5qTE02gJptH0Tzz0GPcu8zQryM3JfhcfFoxRxcE5Zc6WBc=
    - secure: bScKFizEshrC39XzzzXv7IV02y+seAlUlGyl2nMJsM0sqgD1vJawT6ZDBvy68BXRIzams2PN3CbL9hHfTKVxJLM4gSYCdu7KsmZ1IXi4dYhC0oSGz5ejd3k79j4prMO8J+AooMWl20zBB/KgN4PdTWfK1g4TfAHLpAtOFRRl5tI=
addons:
  sauce_connect: true
script: "npm run-script test-travis-$TEST_ENV"
